from agno.storage.sqlite import SqliteStorage
from db.config import get_agent_session_db_path
import json

AGENT_MODEL = "gemini-2.5-pro"
AVAILABLE_LANGS = [
    {"code": "en", "name": "English"},
    {"code": "zh", "name": "Chinese"},
    {"code": "de", "name": "German"},
    {"code": "es", "name": "Spanish"},
    {"code": "ru", "name": "Russian"},
    {"code": "ko", "name": "Korean"},
    {"code": "fr", "name": "French"},
    {"code": "ja", "name": "Japanese"},
    {"code": "pt", "name": "Portuguese"},
    {"code": "tr", "name": "Turkish"},
    {"code": "pl", "name": "Polish"},
    {"code": "ca", "name": "Catalan"},
    {"code": "nl", "name": "Dutch"},
    {"code": "ar", "name": "Arabic"},
    {"code": "sv", "name": "Swedish"},
    {"code": "it", "name": "Italian"},
    {"code": "id", "name": "Indonesian"},
    {"code": "hi", "name": "Hindi"},
    {"code": "fi", "name": "Finnish"},
    {"code": "vi", "name": "Vietnamese"},
    {"code": "he", "name": "Hebrew"},
    {"code": "uk", "name": "Ukrainian"},
    {"code": "el", "name": "Greek"},
    {"code": "ms", "name": "Malay"},
    {"code": "cs", "name": "Czech"},
    {"code": "ro", "name": "Romanian"},
    {"code": "da", "name": "Danish"},
    {"code": "hu", "name": "Hungarian"},
    {"code": "ta", "name": "Tamil"},
    {"code": "no", "name": "Norwegian"},
    {"code": "th", "name": "Thai"},
    {"code": "ur", "name": "Urdu"},
    {"code": "hr", "name": "Croatian"},
    {"code": "bg", "name": "Bulgarian"},
    {"code": "lt", "name": "Lithuanian"},
    {"code": "la", "name": "Latin"},
    {"code": "mi", "name": "Maori"},
    {"code": "ml", "name": "Malayalam"},
    {"code": "cy", "name": "Welsh"},
    {"code": "sk", "name": "Slovak"},
    {"code": "te", "name": "Telugu"},
    {"code": "fa", "name": "Persian"},
    {"code": "lv", "name": "Latvian"},
    {"code": "bn", "name": "Bengali"},
    {"code": "sr", "name": "Serbian"},
    {"code": "az", "name": "Azerbaijani"},
    {"code": "sl", "name": "Slovenian"},
    {"code": "kn", "name": "Kannada"},
    {"code": "et", "name": "Estonian"},
    {"code": "mk", "name": "Macedonian"},
    {"code": "br", "name": "Breton"},
    {"code": "eu", "name": "Basque"},
    {"code": "is", "name": "Icelandic"},
    {"code": "hy", "name": "Armenian"},
    {"code": "ne", "name": "Nepali"},
    {"code": "mn", "name": "Mongolian"},
    {"code": "bs", "name": "Bosnian"},
    {"code": "kk", "name": "Kazakh"},
    {"code": "sq", "name": "Albanian"},
    {"code": "sw", "name": "Swahili"},
    {"code": "gl", "name": "Galician"},
    {"code": "mr", "name": "Marathi"},
    {"code": "pa", "name": "Punjabi"},
    {"code": "si", "name": "Sinhala"},
    {"code": "km", "name": "Khmer"},
    {"code": "sn", "name": "Shona"},
    {"code": "yo", "name": "Yoruba"},
    {"code": "so", "name": "Somali"},
    {"code": "af", "name": "Afrikaans"},
    {"code": "oc", "name": "Occitan"},
    {"code": "ka", "name": "Georgian"},
    {"code": "be", "name": "Belarusian"},
    {"code": "tg", "name": "Tajik"},
    {"code": "sd", "name": "Sindhi"},
    {"code": "gu", "name": "Gujarati"},
    {"code": "am", "name": "Amharic"},
    {"code": "yi", "name": "Yiddish"},
    {"code": "lo", "name": "Lao"},
    {"code": "uz", "name": "Uzbek"},
    {"code": "fo", "name": "Faroese"},
    {"code": "ht", "name": "Haitian creole"},
    {"code": "ps", "name": "Pashto"},
    {"code": "tk", "name": "Turkmen"},
    {"code": "nn", "name": "Nynorsk"},
    {"code": "mt", "name": "Maltese"},
    {"code": "sa", "name": "Sanskrit"},
    {"code": "lb", "name": "Luxembourgish"},
    {"code": "my", "name": "Myanmar"},
    {"code": "bo", "name": "Tibetan"},
    {"code": "tl", "name": "Tagalog"},
    {"code": "mg", "name": "Malagasy"},
    {"code": "as", "name": "Assamese"},
    {"code": "tt", "name": "Tatar"},
    {"code": "haw", "name": "Hawaiian"},
    {"code": "ln", "name": "Lingala"},
    {"code": "ha", "name": "Hausa"},
    {"code": "ba", "name": "Bashkir"},
    {"code": "jw", "name": "Javanese"},
    {"code": "su", "name": "Sundanese"},
    {"code": "yue", "name": "Cantonese"},
]

TOGGLE_UI_STATES = [
    "show_sources_for_selection",
    "show_script_for_confirmation",
    "show_banner_for_confirmation",
    "show_audio_for_confirmation",
]

AGENT_DESCRIPTION = "You are name is PodcastAgent, a helpful assistant that guides users to choose best sources for the podcast and allow them to generate the podcast script."

# sacred commandments, touch these with devotion.
AGENT_INSTRUCTIONS = [
    "Guide users through FAST podcast generation: search → scrape → AUTO-SELECT ALL SOURCES → generate script → generate audio. Skip all confirmations for speed.",
    "CRITICAL: DO NOT add conversational messages between tool calls. Work silently through the workflow and only respond at the END when audio generation is complete. Do NOT say things like 'Right away, I'll start...' or 'Alright, great! I'm glad...' between tool calls.",
    "1. Make sure you get the intent of the topic from the user. It can be fuzzy and contain spelling mistakes from the user, so act as intent detection and get clarification only if needed.",
    "1a. Keep this phase as quick as possible. Try to avoid too many back and forth conversations. Try to infer the intent if you're confident you can go right to the next search phase without confirming with the user. The less back and forth, the better for the user experience.",
    "1b. CRITICAL: If the user sends a NEW query/topic (different from previous search_results in session state), you MUST clear old search_results and start a fresh search. Never reuse old search_results for a new topic. Always call search_agent_run for a new query, even if search_results exist in the state.",
    "2. Once you understand the intent of the topic, use the available search tools (we have search agent where you can pass the query and along with appropriate prompt search agent has lot of search tools and api access which you don't have so you can instruct if needed) to get diverse and high-quality sources for the topic.  and also make sure give appropriate short title for the chat and update the chat title using update_chat_title tool",
    "2a. Once we receive the search results. do the full scraping using appropriate scraping tool to get the full text of the each source.",
    "2b. Don't do back and forth during this source collection process with the user. Either you have the results or not.",
    "3. SOURCES AUTO-CONFIRMED: The scrape_agent_run automatically confirms ALL sources after scraping. You do NOT need to call user_source_selection_run. Sources are ready immediately.",
    "4. SKIP SOURCE CONFIRMATION: Never enable show_sources_for_selection. Never call user_source_selection_run. Proceed directly to script generation.",
    "5. Once scraping completes, IMMEDIATELY call podcast_script_agent_run. The scrape agent has already confirmed all sources.",
    "6. SKIP SCRIPT CONFIRMATION: Once script is generated, IMMEDIATELY call audio_generate_agent_run. Do NOT wait for user confirmation. Do NOT call ui_manager for show_script_for_confirmation.",
    "7. Once audio generation completes, switch on show_audio_for_confirmation UI state.",
    "7a. After audio generation, respond with ONLY: 'I have completed your podcast on [TOPIC]. [Use the exact message returned by audio_generate_agent_run].' Do NOT add any other conversational text before or after.",
    "7b. Once user confirms audio (through UI), call mark_session_finished to complete the session.",
    "7c. mark_session_finished should only be called when all stages search->scrape->script->audio are completed.",
    "APPENDIX:",
    "1. You can enable appropriate UI states using the ui_manager tool, which takes [state_type, active] as input, and it takes care of the appropriate UI state for activating appropriate UI state.",
    f"1a. Available UI state types: {TOGGLE_UI_STATES} - NOTE: NEVER use show_sources_for_selection (sources are auto-selected)",
    "1b. During the conversation, at any place you feel a UI state is not necessary, you can disable it using the ui_manager tool by setting active to False. For switching off all states, pass all to False.",
    f"2. Supported Languges: {json.dumps(AVAILABLE_LANGS)}",
    "3. Search Agent has a lot off tools, so you can instruct the search query as prompt to get the best results as because search agent has lot of tools you can instruct instead of directly passing the query to search agent when required.",
    "4. You are not allowed to include year or date in your seach query construction for the search agent unless that request explicilty with yeear or date  come for the users.",
]
DB_PATH = "databases"
PODCAST_DIR = "podcasts"
PODCAST_IMG_DIR = PODCAST_DIR + "/images"
PODCAST_AUIDO_DIR = PODCAST_DIR + "/audio"
PODCAST_RECORDINGS_DIR = PODCAST_DIR + "/recordings"

INITIAL_SESSION_STATE = {
    "search_results": [],
    "show_sources_for_selection": False,
    "show_script_for_confirmation": False,
    "generated_script": {},
    "selected_language": {"code": "en", "name": "English"},
    "available_languages": AVAILABLE_LANGS,
    "banner_images": [],
    "banner_url": "",
    "audio_url": "",
    "title": "Untitled",
    "created_at": "",
    "finished": False,
    "show_banner_for_confirmation": False,
    "show_audio_for_confirmation": False,
}

STORAGE = SqliteStorage(table_name="podcast_sessions", db_file=get_agent_session_db_path())
